language: node_js
node_js:
- 4.0
before_install:
- npm install -g gulp-cli
install:
- npm install
after_success:
- chmod +x ./bin/create-release-tag.sh
- "./bin/create-release-tag.sh"
branches:
  except:
  - "/^v/"
deploy:
  provider: heroku
  api_key:
    secure: i86ebbP4nNCwOUoEP98PG/L3QqS3JPUu3Fl1d6Jcr40A7Jc8ckI35B04+g0J10MS8CI+pUKJYA8F/nt2mcPD5gwIhKLi7pTVE0w+XMF8yGAwUOaSdAluaWkzD88Yb+TZxsIaY5f+JylkPeMaJTwsbJLYG23bUCJZL3Xz+bTINzOsAbsRsvxp8F3X82bPkR8rRfTpvs1C1ViI/4ar1rJtzTvgLRxYiHjTyCiyiRaLvNJ+RiFNSG5ofUDyxR316yT8pU9TQtbIv9Bz81a60Q7RV0XseK9k1v5Il5H/cJh5k7YTAdq8LcWM8LAOe10macjr/8p++LnM+F1QVmMWfQDBqwJL1e9lU8emZiWtbQWEs/5p24akAhkVqrF+GzfP5t07LN5gWFB0vsu3xrSnlRnPkYNWA2nOMtUxL6F2T14HxpRxSZAjXbTNQaja65PbQ5sUTqVTa0rKvriFLxHLtTOauAEltwhnCdbiUIsMJJ9rzb/uF+IAq72x1nQgZSWv3YQkPkufeEbBuPfzo9F1e4WfJpFknHwtzElGAeagIldJdEYWlDb9HDaaZBIG+nsWPOy8lWWs2E4nv2yBZQOXEaqdGLYvdQrrse6a1gB3wwyE82f1RP1B6NYqZgO3UalXFCNhU3yKMtuqSB5XnTwdmNymN7QSLYGX/QphO1YM0UWjNdc=
  app: lcc-design-system
  on: master
notifications:
  email: false
sudo: false
